Methoden Division und Multiplikation
MichaelMrt03/TestRepo pull request #25
Opened 2024-01-18 20:59 UTC by Sacul65

Methoden Division und Multiplikation hinzugefügt

2024-01-18 21:45 UTC, MichaelMrt03 reviewed
Du hast einen Merge Konflikt, da du deinen branch "lucas" auf der grundlage vom main branch erstellt hast.
Wir programmieren aber den Taschenrechner unabhängig vom main branch.

Das Problem wäre verhindert worden, wenn du in taschenrechner gegangen wärst und anschließend `git pull origin taschenrechner` gemacht hättest. Damit hättest du lokal die aktuellste Version vom taschenrechner.

Jetzt musst du auf der dieser Grundlage einen neuen branch für dein neues feature erstellen:
```
git checkout taschenrechner
git branch feature-multiplizieren-addieren
git checkout feature-multiplizieren-addieren
```
In diesem branch kannst du nun deine Methoden hinzufügen und anschließend pushen und den pull request stellen.

**Goldene Regel:**

> Pull before Push

2024-01-18 21:50 UTC, MichaelMrt03 reviewed
Ich sehe gerade in der commit-history dass du sogar einen merge durchgeführt hast von taschenrechner in lucas. Das war richtig!

Während du in dem taschenrechner branch warst hättest du nur einmal deinen lokalen taschenrechner branch aktualisieren müssen und es wäre alles perfekt.
Während du in im Taschenrechner branch bist:
`git pull origin taschenrechner`

2024-01-19 12:18 UTC, ozi5700 requested changes
Lös deinen Merge Konflikt @Sacul65

2024-01-19 13:22 UTC, MichaelMrt03 commented
Die ganze commit historie und die Branchstruktur ist kaputt. Daher einmal neu machen mit einem auf "taschenrechner" basierenden branch

2024-01-19 13:22 UTC, closed without merging